// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Assignment - A role attached to an user
type Assignment struct {
	Roles []string `json:"roles,omitempty"`
	// Id of a user
	UserID *string `json:"user_id,omitempty"`
}
