// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"time"
)

type OrgRoleType string

const (
	OrgRoleTypeOrgRole OrgRoleType = "org_role"
)

func (e OrgRoleType) ToPointer() *OrgRoleType {
	return &e
}

func (e *OrgRoleType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "org_role":
		*e = OrgRoleType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OrgRoleType: %v", v)
	}
}

// OrgRole - A role automatically applied to all users in an organization.
type OrgRole struct {
	// date and time then the role will expire
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// List of grants (permissions) applied to the role
	Grants []Grant `json:"grants"`
	// Format: <organization_id>:<slug>
	ID string `json:"id"`
	// Human-friendly name for the role
	Name string `json:"name"`
	// Id of an organization
	OrganizationID string `json:"organization_id"`
	// URL-friendly name for the role
	Slug string      `json:"slug"`
	Type OrgRoleType `json:"type"`
}
