// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"time"
)

type PartnerRoleTypeEnum string

const (
	PartnerRoleTypeEnumPartnerRole PartnerRoleTypeEnum = "partner_role"
)

func (e PartnerRoleTypeEnum) ToPointer() *PartnerRoleTypeEnum {
	return &e
}

func (e *PartnerRoleTypeEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "partner_role":
		*e = PartnerRoleTypeEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PartnerRoleTypeEnum: %v", v)
	}
}

// PartnerRole - A role that appears in another organization's role list that can be assigned but not modified by the partner organization.
type PartnerRole struct {
	// date and time then the role will expire
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// List of grants (permissions) applied to the role
	Grants []Grant `json:"grants"`
	// Format: <organization_id>:<slug>
	ID string `json:"id"`
	// Human-friendly name for the role
	Name string `json:"name"`
	// Id of an organization
	OrganizationID string  `json:"organization_id"`
	PartnerOrgID   *string `json:"partner_org_id,omitempty"`
	// URL-friendly name for the role
	Slug string              `json:"slug"`
	Type PartnerRoleTypeEnum `json:"type"`
}
