// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"fmt"
	"time"
)

type PartnerRoleTypeEnum string

const (
	PartnerRoleTypeEnumPartnerRole PartnerRoleTypeEnum = "partner_role"
)

// PartnerRole - A role that appears in another organization's role list that can be assigned but not modified by the partner organization.
type PartnerRole struct {
	// date and time then the role will expire
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// List of grants (permissions) applied to the role
	Grants []Grant `json:"grants"`
	// Format: <organization_id>:<slug>
	ID string `json:"id"`
	// Human-friendly name for the role
	Name string `json:"name"`
	// Id of an organization
	OrganizationID string  `json:"organization_id"`
	PartnerOrgID   *string `json:"partner_org_id,omitempty"`
	// URL-friendly name for the role
	Slug string              `json:"slug"`
	Type PartnerRoleTypeEnum `json:"type"`
}

func NewPartnerRole(input interface{}) (*PartnerRole, error) {
	mapInput, ok := input.(map[string]interface{})
	if !ok {
		return nil, fmt.Errorf("PartnerRole: Expected input to be a map[string]interface{}")
	}
	expiresAt := new(time.Time)
	if _, ok = mapInput["expires_at"]; !ok {
		expiresAt = nil
	} else {
		*expiresAt, ok = mapInput["expires_at"].(time.Time)
		if !ok {
			return nil, fmt.Errorf("PartnerRole: unexpected type for ExpiresAt. Expected time.Time but was %T", mapInput["expires_at"])
		}
	}
	if _, ok = mapInput["grants"]; !ok {
		return nil, fmt.Errorf("PartnerRole: Grants is required, but was not found")
	}
	var grants []Grant
	grantsTmp, ok := mapInput["grants"].([]interface{})
	if !ok {
		return nil, fmt.Errorf("PartnerRole: unexpected type for Grants. Expected []Grant but was %T", mapInput["grants"])
	}
	for _, grantsItemRaw := range grantsTmp {
		grantsItemPtr, err := NewGrant(grantsItemRaw)
		if err != nil {
			return nil, err
		}
		grantsItem := *grantsItemPtr
		grants = append(grants, grantsItem)
	}
	if _, ok = mapInput["id"]; !ok {
		return nil, fmt.Errorf("PartnerRole: ID is required, but was not found")
	}
	var id string
	id, ok = mapInput["id"].(string)
	if !ok {
		return nil, fmt.Errorf("PartnerRole: unexpected type for ID. Expected string but was %T", mapInput["id"])
	}
	if _, ok = mapInput["name"]; !ok {
		return nil, fmt.Errorf("PartnerRole: Name is required, but was not found")
	}
	var name string
	name, ok = mapInput["name"].(string)
	if !ok {
		return nil, fmt.Errorf("PartnerRole: unexpected type for Name. Expected string but was %T", mapInput["name"])
	}
	if _, ok = mapInput["organization_id"]; !ok {
		return nil, fmt.Errorf("PartnerRole: OrganizationID is required, but was not found")
	}
	var organizationID string
	organizationID, ok = mapInput["organization_id"].(string)
	if !ok {
		return nil, fmt.Errorf("PartnerRole: unexpected type for OrganizationID. Expected string but was %T", mapInput["organization_id"])
	}
	partnerOrgID := new(string)
	if _, ok = mapInput["partner_org_id"]; !ok {
		partnerOrgID = nil
	} else {
		*partnerOrgID, ok = mapInput["partner_org_id"].(string)
		if !ok {
			return nil, fmt.Errorf("PartnerRole: unexpected type for PartnerOrgID. Expected string but was %T", mapInput["partner_org_id"])
		}
	}
	if _, ok = mapInput["slug"]; !ok {
		return nil, fmt.Errorf("PartnerRole: Slug is required, but was not found")
	}
	var slug string
	slug, ok = mapInput["slug"].(string)
	if !ok {
		return nil, fmt.Errorf("PartnerRole: unexpected type for Slug. Expected string but was %T", mapInput["slug"])
	}
	if _, ok = mapInput["type"]; !ok {
		return nil, fmt.Errorf("PartnerRole: Type is required, but was not found")
	}
	var typeString string
	typeString, ok = mapInput["type"].(string)
	if !ok {
		return nil, fmt.Errorf("PartnerRole: unexpected type for Type. Expected string but was %T", mapInput["type"])
	}
	type1 := PartnerRoleTypeEnum(typeString)
	if type1 != PartnerRoleTypeEnumPartnerRole {
		return nil, fmt.Errorf("PartnerRole: unexpected value for Type. Expected one of TypePartnerRole but was %s", mapInput["type"])
	}
	out := &PartnerRole{
		ExpiresAt:      expiresAt,
		Grants:         grants,
		ID:             id,
		Name:           name,
		OrganizationID: organizationID,
		PartnerOrgID:   partnerOrgID,
		Slug:           slug,
		Type:           type1,
	}

	return out, nil
}
