// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type RoleSearchInput struct {
	// The Number of roles to return
	Limit *float64 `json:"limit,omitempty"`
	// The number of roles to skip before starting to collect the result set
	Offset *float64 `json:"offset,omitempty"`
	// List of organization ids to filter by
	OrgIds []string `json:"org_ids,omitempty"`
	// Input to search across fields
	Query *string `json:"query,omitempty"`
	// List of role ids to filter by
	RoleIds []string `json:"role_ids,omitempty"`
	// List of role slugs to filter by
	Slugs []string `json:"slugs,omitempty"`
}
