// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"time"
)

type ShareRoleTypeEnum string

const (
	ShareRoleTypeEnumShareRole ShareRoleTypeEnum = "share_role"
)

func (e *ShareRoleTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "share_role":
		*e = ShareRoleTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for ShareRoleTypeEnum: %s", s)
	}
}

// ShareRole - A role that can be assigned to users in other organizations for sharing purposes.
type ShareRole struct {
	// date and time then the role will expire
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// List of grants (permissions) applied to the role
	Grants []Grant `json:"grants"`
	// Format: <organization_id>:<slug>
	ID string `json:"id"`
	// Human-friendly name for the role
	Name string `json:"name"`
	// Id of an organization
	OrganizationID string `json:"organization_id"`
	// URL-friendly name for the role
	Slug string            `json:"slug"`
	Type ShareRoleTypeEnum `json:"type"`
}
