// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"time"
)

type UserRoleType string

const (
	UserRoleTypeUserRole UserRoleType = "user_role"
)

func (e UserRoleType) ToPointer() *UserRoleType {
	return &e
}

func (e *UserRoleType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "user_role":
		*e = UserRoleType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UserRoleType: %v", v)
	}
}

// UserRole - A standard user role. Must be explicitly assigned to users.
type UserRole struct {
	// date and time then the role will expire
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// List of grants (permissions) applied to the role
	Grants []Grant `json:"grants"`
	// Format: <organization_id>:<slug>
	ID string `json:"id"`
	// Human-friendly name for the role
	Name string `json:"name"`
	// Id of an organization
	OrganizationID string `json:"organization_id"`
	// URL-friendly name for the role
	Slug string       `json:"slug"`
	Type UserRoleType `json:"type"`
}
