// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type Role struct {
	UserRole    *UserRole    `tfsdk:"user_role"`
	OrgRole     *OrgRole     `tfsdk:"org_role"`
	ShareRole   *ShareRole   `tfsdk:"share_role"`
	PartnerRole *PartnerRole `tfsdk:"partner_role"`
}
