// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type OrgRole struct {
	ExpiresAt      types.String `tfsdk:"expires_at"`
	Grants         []Grant      `tfsdk:"grants"`
	ID             types.String `tfsdk:"id"`
	Name           types.String `tfsdk:"name"`
	OrganizationID types.String `tfsdk:"organization_id"`
	Slug           types.String `tfsdk:"slug"`
	Type           types.String `tfsdk:"type"`
}
