// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AssignRolesRequest struct {
	RequestBody []string `request:"mediaType=application/json"`
	UserID      string   `pathParam:"style=simple,explode=false,name=userId"`
}

type AssignRolesResponse struct {
	// ok
	Assignments []string
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
