// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"fmt"
	"net/http"
)

type AssignRolesPathParams struct {
	UserID string `pathParam:"style=simple,explode=false,name=userId"`
}

func NewAssignRolesPathParams(input interface{}) (*AssignRolesPathParams, error) {
	mapInput, ok := input.(map[string]interface{})
	if !ok {
		return nil, fmt.Errorf("assignRolesPathParams: Expected input to be a map[string]interface{}")
	}
	if _, ok = mapInput["userId"]; !ok {
		return nil, fmt.Errorf("assignRolesPathParams: UserID is required, but was not found")
	}
	var userID string
	userID, ok = mapInput["userId"].(string)
	if !ok {
		return nil, fmt.Errorf("assignRolesPathParams: unexpected type for UserID. Expected string but was %T", mapInput["userId"])
	}
	out := &AssignRolesPathParams{
		UserID: userID,
	}

	return out, nil
}

type AssignRolesRequest struct {
	PathParams AssignRolesPathParams
	Request    []string `request:"mediaType=application/json"`
}

func NewAssignRolesRequest(input interface{}) (*AssignRolesRequest, error) {
	mapInput, ok := input.(map[string]interface{})
	if !ok {
		return nil, fmt.Errorf("assignRolesRequest: Expected input to be a map[string]interface{}")
	}
	if _, ok = mapInput["PathParams"]; !ok {
		return nil, fmt.Errorf("assignRolesRequest: PathParams is required, but was not found")
	}
	pathParamsPtr, err := NewAssignRolesPathParams(mapInput["PathParams"])
	if err != nil {
		return nil, err
	}
	pathParams := *pathParamsPtr
	var request []string
	if _, ok = mapInput["Request"]; ok {
		requestTmp, ok := mapInput["Request"].([]interface{})
		if !ok {
			return nil, fmt.Errorf("assignRolesRequest: unexpected type for Request. Expected []string but was %T", mapInput["Request"])
		}
		for _, requestItemRaw := range requestTmp {
			var requestItem string
			requestItem, ok = requestItemRaw.(string)
			if !ok {
				return nil, fmt.Errorf("assignRolesRequest: unexpected type for RequestItem. Expected string but was %T", requestItemRaw)
			}
			request = append(request, requestItem)
		}
	}
	out := &AssignRolesRequest{
		PathParams: pathParams,
		Request:    request,
	}

	return out, nil
}

type AssignRolesResponse struct {
	// ok
	Assignments []string
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}

func NewAssignRolesResponse(input interface{}) (*AssignRolesResponse, error) {
	mapInput, ok := input.(map[string]interface{})
	if !ok {
		return nil, fmt.Errorf("assignRolesResponse: Expected input to be a map[string]interface{}")
	}
	var assignments []string
	if _, ok = mapInput["Assignments"]; ok {
		assignmentsTmp, ok := mapInput["Assignments"].([]interface{})
		if !ok {
			return nil, fmt.Errorf("assignRolesResponse: unexpected type for Assignments. Expected []string but was %T", mapInput["Assignments"])
		}
		for _, assignmentsItemRaw := range assignmentsTmp {
			var assignmentsItem string
			assignmentsItem, ok = assignmentsItemRaw.(string)
			if !ok {
				return nil, fmt.Errorf("assignRolesResponse: unexpected type for AssignmentsItem. Expected string but was %T", assignmentsItemRaw)
			}
			assignments = append(assignments, assignmentsItem)
		}
	}
	if _, ok = mapInput["ContentType"]; !ok {
		return nil, fmt.Errorf("assignRolesResponse: ContentType is required, but was not found")
	}
	var contentType string
	contentType, ok = mapInput["ContentType"].(string)
	if !ok {
		return nil, fmt.Errorf("assignRolesResponse: unexpected type for ContentType. Expected string but was %T", mapInput["ContentType"])
	}
	if _, ok = mapInput["StatusCode"]; !ok {
		return nil, fmt.Errorf("assignRolesResponse: StatusCode is required, but was not found")
	}
	if _, ok = mapInput["StatusCode"]; !ok {
		return nil, fmt.Errorf("assignRolesResponse: StatusCode is required, but was not found")
	}
	var statusCodeFloat64 float64
	statusCodeFloat64, ok = mapInput["StatusCode"].(float64)
	if !ok {
		return nil, fmt.Errorf("assignRolesResponse: unexpected type for StatusCode. Expected float64 but was %T", mapInput["StatusCode"])
	}
	var statusCode int
	if statusCodeFloat64 != float64(int(statusCodeFloat64)) {
		return nil, fmt.Errorf("assignRolesResponse: unexpected value for integer StatusCode. Got %#v", mapInput["StatusCode"])
	} else {
		statusCode = int(statusCodeFloat64)
	}
	rawResponse := new(http.Response)
	if _, ok = mapInput["RawResponse"]; !ok {
		rawResponse = nil
	} else {
		*rawResponse, ok = mapInput["RawResponse"].(http.Response)
		if !ok {
			return nil, fmt.Errorf("assignRolesResponse: unexpected type for RawResponse. Expected http.Response but was %T", mapInput["RawResponse"])
		}
	}
	out := &AssignRolesResponse{
		Assignments: assignments,
		ContentType: contentType,
		StatusCode:  statusCode,
		RawResponse: rawResponse,
	}

	return out, nil
}
