// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type AssignRolesPathParams struct {
	UserID string `pathParam:"style=simple,explode=false,name=userId"`
}

type AssignRolesRequest struct {
	PathParams AssignRolesPathParams
	Request    []string `request:"mediaType=application/json"`
}

type AssignRolesResponse struct {
	// ok
	Assignments []string
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
