// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"epilot-permission/internal/sdk/pkg/models/shared"
	"net/http"
)

type DeleteRoleRequest struct {
	RoleID string `pathParam:"style=simple,explode=false,name=roleId"`
}

type DeleteRoleResponse struct {
	ContentType string
	// ok
	Role        *shared.Role
	StatusCode  int
	RawResponse *http.Response
}
