// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetAssignedRolesForUserPathParams struct {
	UserID string `pathParam:"style=simple,explode=false,name=userId"`
}

type GetAssignedRolesForUserRequest struct {
	PathParams GetAssignedRolesForUserPathParams
}

type GetAssignedRolesForUserResponse struct {
	// ok
	Assignments []string
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
