// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"epilotpermissions/internal/sdk/pkg/models/shared"
	"net/http"
)

// ListAllRoles200ApplicationJSON - ok
type ListAllRoles200ApplicationJSON struct {
	Roles []shared.Role `json:"roles,omitempty"`
}

type ListAllRolesResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// ok
	ListAllRoles200ApplicationJSONObject *ListAllRoles200ApplicationJSON
}
