// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"epilotpermissions/internal/sdk/pkg/models/shared"
	"net/http"
)

// ListCurrentRoles200ApplicationJSON - ok
type ListCurrentRoles200ApplicationJSON struct {
	Roles []shared.Role `json:"roles,omitempty"`
}

type ListCurrentRolesResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// ok
	ListCurrentRoles200ApplicationJSONObject *ListCurrentRoles200ApplicationJSON
}
