// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"epilot-permission/internal/sdk/pkg/models/shared"
	"net/http"
)

// ListAllAssignments200ApplicationJSON - ok
type ListAllAssignments200ApplicationJSON struct {
	Assignments []shared.Assignment `json:"assignments,omitempty"`
}

type ListAllAssignmentsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// ok
	ListAllAssignments200ApplicationJSONObject *ListAllAssignments200ApplicationJSON
}
