// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"epilotpermissions/internal/sdk/pkg/models/shared"
	"net/http"
)

type PutRolePathParams struct {
	RoleID string `pathParam:"style=simple,explode=false,name=roleId"`
}

type PutRoleRequest struct {
	PathParams PutRolePathParams
	Request    *shared.Role `request:"mediaType=application/json"`
}

type PutRoleResponse struct {
	ContentType string
	// ok
	Role        *shared.Role
	StatusCode  int
	RawResponse *http.Response
}
