// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"epilotpermissions/internal/sdk/pkg/models/shared"
	"net/http"
)

type RemoveAssignmentPathParams struct {
	RoleID string `pathParam:"style=simple,explode=false,name=roleId"`
	UserID string `pathParam:"style=simple,explode=false,name=userId"`
}

type RemoveAssignmentRequest struct {
	PathParams RemoveAssignmentPathParams
}

type RemoveAssignmentResponse struct {
	// ok
	Assignment  *shared.Assignment
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
